name: flutter_jsonable
description: A new Flutter package provide jsonable APIs.
version: 1.0.1
homepage: https://github.com/flutter-thrio/flutter_jsonable

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
